version: '3'
# docker-compose run --service-ports --rm go-dev

services:

  go-dev:
    build: .
    image: go-dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ${GOPATH}/src:/go/src
      - go-bin:/go/bin
    networks:
      - go-dev

networks:
  go-dev:

volumes:
  go-bin:
